packages = {'src/contrib/bookkeeper/src/java/org/apache/bookkeeper/proto'
'src/contrib/bookkeeper/src/java/org/apache/bookkeeper/streaming'
'src/contrib/bookkeeper/src/java/org/apache/bookkeeper/util'
'src/contrib/bookkeeper/src/java/org/apache/bookkeeper/client'
'src/contrib/bookkeeper/src/java/org/apache/bookkeeper/bookie'
'src/contrib/zooinspector/src/java/org/apache/zookeeper/inspector/manager'
'src/contrib/zooinspector/src/java/org/apache/zookeeper/inspector'
'src/contrib/zooinspector/src/java/org/apache/zookeeper/inspector/gui'
'src/contrib/zooinspector/src/java/org/apache/zookeeper/inspector/gui/nodeviewer'
'src/contrib/zooinspector/src/java/org/apache/zookeeper/retry'
'src/contrib/rest/src/java/org/apache/zookeeper/server/jersey/resources'
'src/contrib/rest/src/java/org/apache/zookeeper/server/jersey/jaxb'
'src/contrib/rest/src/java/org/apache/zookeeper/server/jersey'
'src/contrib/fatjar/src/java/org/apache/zookeeper/util'
'src/recipes/lock/src/java/org/apache/zookeeper/recipes/lock'
'src/recipes/queue/src/java/org/apache/zookeeper/recipes/queue'}
